### ISSUE TITLE
Sequencing technologies readings

### ISSUE THREAD

**Issue by isgilman** [Yale-EEB723/syllabus#1]
Here are a few options for the reading for class on 24 January. 

* Coming of age: ten years of next-generation sequencing technologies. Sara Goodwin, John D. McPherson & W. Richard McCombie. Nature Reviews Genetics. (2016) https://doi.org/10.1038/nrg.2016.49
* High-Throughput Sequencing Technologies. Jason A. Reuter, Damek V. Spacek, & Michael P. Snyder. Molecular Cell. (2015) https://doi.org/10.1016/j.molcel.2015.05.004
* The sequence of sequencers: The history of sequencing DNA. James M. Heather & Benjamin Chain. Molecular Cell. (2015) https://doi.org/10.1016/j.molcel.2015.05.004

This first is a bit longer but a little more recent with better figures of how various technologies work.

**Comment by zrlewis** [comment]
This is a short review of sequencing tech, with a historical perspective:

- [DNA sequencing at 40: past, present and future](https://www.nature.com/articles/nature24286)

**Comment by caseywdunn** [comment]
Thanks @isgilman and @zrlewis . I added the references to the syllabus and fleshed out the main points to discuss in the class as a whole. @isgilman - aim to to focus on the paper for the first 15 minutes or so of class. You can prepare some slides if you like, but this is not necessary. Whatever items in the syllabus we don't get to during the paper discussion I'll then lead a discussion on. TL;DR - @isgilman cover whatever you think is best during the 15 minutes you lead discussion, I'll work around your presentation and take care of the rest.
