### ISSUE TITLE
Publications: Using nanopore for rapid biodiversity assessment AND where is genomics going next?

### ISSUE THREAD

**Issue by diego-ellis-soto** [Yale-EEB723/syllabus#4]
Interesting papers which could be added to the publication list:

Pomerantz et al. 2018. Real-time DNA barcoding in a rainforest using nanopore sequencing: opportunities for rapid biodiversity assessments and local capacity building GigaScience. https://academic.oup.com/gigascience/article/7/4/giy033/4958980

Cheifet 2019. Where is genomics going next?  Genome Biology.
https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-019-1626-2

**Comment by caseywdunn** [comment]
Just added them to the syllabus, thanks!
